### ISSUE TITLE
Update font on outdatedbrowser.com

### ISSUE THREAD

**Issue by JosefJezek** [burocratik/outdated-browser#135]
Could you update font on page outdatedbrowser.com? Czech lang have not char Č and Ř.

**Comment by JosefJezek** [comment]
And not detect my Czech lang, default lang is English on your page.

![selection_006](https://cloud.githubusercontent.com/assets/2110319/5595065/46083bda-9269-11e4-9756-989efd35acc2.png)

On Ubuntu 14.04.1, Chrome Version 39.0.2171.71 (64-bit)

![selection_005](https://cloud.githubusercontent.com/assets/2110319/5595040/94c5b28a-9268-11e4-910d-5b51e850aa54.png)

```
.da-slide .da-txt h2 {
font-family: 'Gotham SSm A', 'Gotham SSm B', Helvetica, Arial, sans-serif;
```

**Comment by alexandre-works** [comment]
The font we are using has those accents.
http://www.typography.com/fonts/gotham/characters/gothamscreensmartmedium

Maybe the reason is not detecting the  Czech lang, is because I made a mistake with the lang atribute (cz insted of cs). I will try that out and ask your feedback, if you dont mind.
Cheers

**Comment by alexprg** [comment]
Thanks @JosefJezek 
We just fixed this issue, if you find any other bug with accents feel free to shout at us ;)
Cheers
