### ISSUE TITLE
Not displaying correctly on IE8 and below

### ISSUE THREAD

**Issue by abelthomas** [burocratik/outdated-browser#184]
I get a weird error saying "h.children.0.style is null or not an object". Could this be because I'm not calling the JS early enough? Should I be inputting the JS file and the plugin callout in the head of my document? Any help is greatly appreciated!

**Comment by alexprg** [comment]
Hi @abelthomas 
Indeed because the way older browsers deal with javascript, my advise is:
"Important: Because of old browsers (e.g. IE6, IE7), we recommend to implement this plugin before any other javascripts (plugins or your own scripts) — these browsers have "strange" js errors and the plugin may not be working as intended."

**Comment by abelthomas** [comment]
Ok I'll try including this as the first script on the page. Thanks for the prompt response, and great work on this plugin!

**Comment by alexprg** [comment]
my pleasure
