### ISSUE TITLE
The Ukrainian language has wrong ISO code

### ISSUE THREAD

**Issue by seagullua** [burocratik/outdated-browser#209]
The Ukrainian language has ISO code ```uk``` but not ```ua```. I am detecting plugin version based on browser language and when I am redirecting to http://outdatedbrowser.com/uk I see the english version.

You can check https://en.wikipedia.org/wiki/Ukrainian_language Language code section 
ISO 639-1	uk

**Comment by Pryx** [comment]
Same problem with Czech... Guess they went with another standard (https://en.wikipedia.org/wiki/ISO_3166) It would be nice to switch it to ISO 639 as it is intended for language codes and ISO 3166 for country codes (which doesn't really make sense to use here)... Would love if this were possible. 

cc @alexprg

**Comment by damianvila** [comment]
I think the best solution will be to use IETF language tags (based on ISO 639 language codes), instead of ISO 3166 country codes: https://en.wikipedia.org/wiki/IETF_language_tag
It's what browsers use by default. (Arabic: ar, Portuguese: pt, Brazilian Portuguese: pt-br, Mandarin: zh, Taiwanese Mandarin: zh-tw, etc.)
This way, you can simply use the HTML lang attribute used by the browser to check the language and deliver the corresponding page.

**Comment by alexprg** [comment]
Para as línguas usamos o recomendado pelo W3C ISO 639-1 Language Codes para o html,
para o url usamos o do pais. 
Na altura tive a duvida se deviamos usar tb o da lingia no url, mas para a maioria das pessoas ajudar ser a lingua e nao o codigo que ninguem conhece. Vimos isso
e optamos por uma abordagem tipo a da BBC.  Tivemos essa duvida no chines e com taiwan, que o codigo é chines tradicional mas é um chines diferente do tradicional que
tambem existe na china.

**Comment by Pryx** [comment]
Well, the conventional approach (IETF language tag) is ISO 639-1 language - ISO 3166 regional code (e.g. cs-CZ, en-US etc.). For languages that have no regional version, the region could be omitted so it is more human-readable. But current approach is really wrong, wouldn't say that it has any important benefits for cases like taiwan chinese and it interferes with a lot of existing implementations. Would probably make a lot of lives easier if you switched it.

**Comment by damianvila** [comment]
@alexprg Well, our main problem was with the site (http://outdatedbrowser.com/). We're rolling a warning of our own (way simpler, based on IE's conditional comments but with translated literals based on language served by our CMS), and wanted to point to the site, since it supports Arabic, which is very useful to us, but since the URLs use a mix of codes ("arabic", "br", etc.), and our CMS will serve the message depending on the language selected by the user (that has no correlation with you scheme), it will require for us to make a query on a table for this correlation, which is impractical.

In the end we will point to http://browsehappy.com/, that has a solid locale set that matches the language codes, but has no Arabic, so we'll have to send those users to the English version (it has Japanese, though, which is also attractive. We're interested in Indonesian, but none of you offer that).

If you ever reconsider, we may point to your page instead of the other, since it's more attractive and has Arabic translation. Cheers.

**Comment by alexprg** [comment]
Hi there,
For several reasons we had to do the current approach, and due to the lack of time we had no chance
to change to ISO 639 for the urls. 
Give us some time and I will update you guys as soon we make that change.
Thank you guys for all the feedback :+1: 
Cheers

**Comment by alexprg** [comment]
Hi guys,
Once again thank you for your feedback. 
We've just updated the website and plugin with IETF language tag)
@damianvila we are trying our best to have the Japanese and Indonesian translations of the website (and all the others that are missing) ;).
cheers

**Comment by alexprg** [comment]
@damianvila Japanese is online http://outdatedbrowser.com/ja. The lang for the plugin is here: https://github.com/burocratik/outdated-browser/blob/develop/outdatedbrowser/lang/ja.html

**Comment by damianvila** [comment]
@alexprg Thanks a lot!
