### ISSUE TITLE
Error: Cannot find module 'outdated-browser'

### ISSUE THREAD

**Issue by Splintex** [burocratik/outdated-browser#234]
I had bug with webpack and outdated-browser npm module

**Comment by ochervak** [comment]
+1

**Comment by brunoamorim** [comment]
Hi guys, 
The actual NPM Outdated Browser plugin was made by a fan of the Outdated Browser and we don't have admin privileges on it in order to update it. 

We have to rebuild an entire new NPM plugin to be always up do date with the official Outdated Browser NPM Plugin. I hope that can be done soon. We'll keep you posted.

**Comment by xakzona** [comment]
let outdatedBrowser = require("exports-loader?outdatedBrowser!outdated-browser/outdatedbrowser/outdatedbrowser");

**Comment by alexdiliberto** [comment]
Bumping thread. Please update NPM version or publish to a modified NPM package name.

**Comment by Deadload** [comment]
Hi guys, sorry for the delay.
Just deployed new NPM package: outdatedbrowser.

Any questions or issues please let us know.


Thks
