### ISSUE TITLE
Why recommend IE11 when visiting from a Windows 10 PC?

### ISSUE THREAD

**Issue by richardthombs** [burocratik/outdated-browser#235]
When I visit outdatedbrowser.com from a Windows 10 PC, I am told that IE 11 is what I should be using.

Surely the correct advise is to use Edge?

**Comment by Kum0ri** [comment]
Hi @richardthombs . Thanks for the comment!

The thing is that users that have windows 10 will likely not go to outdatedbrowser.com coming from the warning of the plugin.
The website is intended to show the most used browsers that are available on the market. 
Since people cannot download edge ( it comes with the os ), the latest browser from Microsoft is ie11 and for that range of users ( windows users without Windows 10 ) the best Microsoft option is still internet explorer 11.

Cheers,
Daniel

**Comment by richardthombs** [comment]
I still think it's mistaken to tell Windows 10 users that IE11 is the latest browser for their OS. The latest browser from Microsoft for Windows 10 users is Edge, not IE11. You're right that they can't choose to download it, but then they can't download IE11 either. So they have a choice between IE11 and Edge and one is very clearly superior and more recent that the other... and the website isn't recommending it.

**Comment by kristianserrano** [comment]
To reiterate the point @Kum0ri is trying to make, a Windows 10 user wouldn't be coming to outdatedbrowser.com at all because they wouldn't see the warning, so there is no issue of telling Windows 10 users that IE11 is the latest browser for their OS.

**Comment by natedunn** [comment]
I see both perspectives here. Maybe some hybrid approach between what we have now (with IE option) and what we see being done with Safari/OS X option ("AVAILABLE ONLY WITH OS X")? At least for the uninformed about how pre-installed browsers work?

**Comment by richardthombs** [comment]
Anything would be good. My problem comes from the fact that in a documentation wiki that describes what browsers we support, we include a link to outdatedbrowser.com. So we're not running the JS code, simply pointing them at the website as a reference tool.

**Comment by kristianserrano** [comment]
I think I'm seeing the problem. You're associating latest browser with the OS, not the latest version of a browser. In this case 11 is the latest version of IE. Edge is a different browser. This site's goal is not to present a market of browsers by OS. It's a site for a tool that notifies users if they're browser is outdated and gives them options to download a modern browser. For your user case, browsehappy.com might be the better option.

**Comment by richardthombs** [comment]
Absolutely. I still can't quite believe that you think that telling folks that IE 11 is the latest browser. Yes it's the latest version of IE, but as far as browsers from Microsoft are concerned, it's now Edge. It's like saying them that the latest version of Netscape Navigator is 9.0 it's factually correct and all, but the world would rather they didn't use it.

**Comment by kristianserrano** [comment]
You're asking for the addition of a new browser, not the latest version. Additionally, that new browser is unavailable to anyone who would likely see the notification. As I stated, you're forgetting the purpose of the tool and site. Specifically, it's targeted audience doesn't include Windows 10 users.

You said yourself that you're not using the script; you're just linking to the site from a wiki. If you want a catalog of all currently available browsers, there are other sites for that.

**Comment by natedunn** [comment]
Practically, I agree with @kristianserrano, and I will be using the site as is. I think this just speaks to the complication of supporting two browsers the way Microsoft does. However I do understand what @richardthombs is trying to say. It wouldn't be that difficult to provide better context for the current state of browsers no matter what browser you actively use. But since that seems unlikely to change for this, @richardthombs perhaps you could cold fork the repo and/or create your own tool that meets your needs? I also think browsehappy.com is a decent alternative.
