### ISSUE TITLE
Version 1.1.3 isn't in NPM?

### ISSUE THREAD

**Issue by tiagoporto** [burocratik/outdated-browser#244]

**Comment by brunoamorim** [comment]
Hi @tiagoporto , 
The actual NPM Outdated Browser plugin was made by a fan of the Outdated Browser and we don't have admin privileges on it in order to update it.

We have to rebuild an entire new NPM plugin to be always up do date with the official Outdated Browser NPM Plugin. I hope that can be done soon. We'll keep you posted.
