### ISSUE TITLE
Add Microsoft Edge

### ISSUE THREAD

**Issue by aarongustafson** [burocratik/outdated-browser#256]

**Comment by ohepworthbell** [comment]
Further from that, I think it would be better to have IE11 scrapped and replaced with Edge, and not show IE11 at all.

IE11 still lacks support for many modern technologies (especially responsive technologies, such as the <picture> tag, an inability to properly scale SVG images properly, buggy-at-best CSS flexbox support or any JavaScript ES6 markups, all of which Edge largely supports) and was released almost 3 years ago with no further intention of updates (from what I can see), as opposed to the most recent version of Edge (14), which was released 5 months ago with Edge 15 in the pipeline.

Also worth noting that Edge starts at version 12, so it's clearly just IE re-branded. I think it's time to scrap IE11 for good and encourage people to use Edge or almost anything else.

**Comment by franklinyu** [comment]
@ohepworthbell Maybe because Edge requires Windows 10?

**Comment by danbohea** [comment]
@franklinyu You're answering a question that wasn't asked. Either way, this project still needs to _add_ Edge.

**Comment by pedrosanta** [comment]
+1
just re-peeked the project and yes, IE should definitely be replaced for Edge on this one.

**Comment by Kum0ri** [comment]
Hi ppl, edge/ie is a sensitive issue. We updated the website, for what we think is the best compromise. For the users that land in http://outdatedbrowser.com with IE10 browser or less, the website will suggest the latest Microsoft website that this user can download ( IE11 ), for users that land with IE11 the website will suggest that they download Windows 10 to use Microsoft Edge, since that's the only way that they have to update to the latest Microsoft browser, that is not IE11. For every other browser the website will suggest always the latest Microsoft browser ( Edge ).

Cheers!

**Comment by pedrosanta** [comment]
@Kum0ri sounds like an interesting compromise. Cool beans! 👍 

Any chance for you to expand on that 'edge/ie is a sensitive issue'? 🙂

**Comment by Kum0ri** [comment]
Hi @pedrosanta ,
Well, this is a sensitive issue because, unlike Apple, microsoft rolled out a new browser, one that is not possible to download, it's part of Windows 10 and kept IE11 as a downloadable browser. We all know that IE11 is an outdated browser, but it's the last browser that people can download from Microsoft.

We know too, that a great share of people that land in outdatedbrowser.com because they have an outdated browser is people that have ie9 ie10 and so on, and probably would want to keep a microsoft browser. So we only have ie11 as an option for them.

Hope that made this clear ;) 

Soon this will not be an issue, but for know i think that this is the best compromise.

**Comment by pedrosanta** [comment]
@Kum0ri got it, makes sense, thanks! 👍
