### ISSUE TITLE
Remove Internet Explorer entirely

### ISSUE THREAD

**Issue by adamn** [burocratik/outdated-browser#268]
Remove Internet Explorer from the homepage entirely.  Edge is great for Windows 10 users and those with older versions of Windows just have to use another browser to get a modern experience anyway.

For our application, that requires Edge or FF/Chrome/Safari, we cannot use this package until this is changed.

#253 or #251 could take the space of IE (or even Brave).

**Comment by ArtuGit** [comment]
Actual

**Comment by JohnWeisz** [comment]
Same here, as we are now considering IE11 as an outdated, obsolete browser and would suggest people update to Edge if they prefer a Microsoft browser. We would be happy to use this project as it is aesthetically on the same level as our design, but the presence of IE11 is a no-go.

**Comment by Kum0ri** [comment]
Hi ppl, edge/ie is a sensitive issue. We updated the website, for what we think is the best compromise. For the users that land in http://outdatedbrowser.com with IE10 browser or less, the website will suggest the latest Microsoft website that this user can download ( IE11 ), for users that land with IE11 the website will suggest that they download Windows 10 to use Microsoft Edge, since that's the only way that they have to update to the latest Microsoft browser, that is not IE11. For every other browser the website will suggest always the latest Microsoft browser ( Edge ).

Cheers!
