### ISSUE TITLE
IE9 supports transform?

### ISSUE THREAD

**Issue by atorkhov** [burocratik/outdated-browser#61]
Just a question. According to http://caniuse.com/transforms2d and http://www.css3files.com/transform/ IE9 did support -ms-transform attribute... Though it does correctly show notice. Does your code relies on bug in IE?

**Comment by thuff** [comment]
Looks like this is due to the camel case of the Vendor prefixes. The Ms in the string is concatenated to look for a style property of MsTransform. msTransform would return a true, which would in fact render this check invalid.

On further checking, the newest version of Chrome does allow the casing to be either 'Webkit' or 'webkit'. You can see that from this code sample.

```
element.style.webkitAnimation
""
element.style.webkitAnimation = 'test'
"test"
element.style.WebkitAnimation
"test"
```

This isn't an IE bug, it is a bug in the plug-in logic.
